name: Advisory

options:
  bundleIdPrefix: com.manigorman
  xcodeVersion: 13.3.1
  deploymentTarget:
    iOS: '14.0'
  groupSortPosition: top
  generateEmptyDirectories: true

configs:
    Develop: debug
    Enterprise: release

targets:
  Advisory:
    type: application
    platform: iOS
    settings:
      base:
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1
    sources:
       - Advisory
    postCompileScripts:
      - script: "if which \"${PODS_ROOT}/SwiftLint/swiftlint\" > /dev/null; then\n\"${PODS_ROOT}/SwiftLint/swiftlint\"\nelse\necho \"warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint\"\nfi"
        name: SwiftLint
    postBuildScripts:
    - script: |
        TAGS="TODO:|FIXME:"
        echo "searching ${SRCROOT} for ${TAGS}"
        find "${SRCROOT}" \( -name "*.swift" \) \( -not -path "*/Pods/*" \) -print0 | xargs -0 egrep --with-filename --line-number --only-matching "($TAGS).*\$" | perl -p -e "s/($TAGS)/ warning: \$1/"
      name: Highlight TODOs and FIXMEs
schemes:
    Advisory:
        build:
            targets:
                Advisory: Advisory
        run:
            config: Develop
        profile:
            config: Develop
        analyze:
            config: Develop
        archieve:
            config: Enterprise

